apiVersion: v1
kind: ConfigMap
metadata:
  name: basic-configmap
  namespace: demo-basic
data:
  GREETING: "WLECOME TO YOUR CLUSTER"
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-secret
  namespace: demo-basic
type: Opaque
stringData:
  API_KEY: "Secret-123"